name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
      
      - name: Deploy to Digital Ocean
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: ${{ secrets.DO_APP_NAME }}
          token: ${{ secrets.DO_API_TOKEN }}
          images: '[{"name": "scbc-app", "registry_type": "DOCKERHUB", "repository": "react-app", "tag": "${{ github.sha }}"}]' 